version: "3.8"
services:
  backend:
    build:
      context: .
      target: BUILD_SERVER
    image: karta0989006/dms-server
    environment:
      - NODE_ENV=production
    ports:
      - 80:5001
    networks:
      - dms-backend
    # command: ["npm", "run", "dev"]
    command: ["npm", "start"]

networks:
  dms-backend:
